%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosPropertyService_ConstraintNotSupported
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosProperty/src/CosProperty.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosPropertyService_ConstraintNotSupported').
-ic_compiled("4_4_2").


-include("CosPropertyService.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosPropertyService/ConstraintNotSupported:1.0",
                   "ConstraintNotSupported",[]}.

%% returns id
id() -> "IDL:omg.org/CosPropertyService/ConstraintNotSupported:1.0".

%% returns name
name() -> "CosPropertyService_ConstraintNotSupported".



