%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosTime_TimeUnavailable
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosTime_TimeUnavailable').
-ic_compiled("4_4_2").


-include("CosTime.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosTime/TimeUnavailable:1.0",
                   "TimeUnavailable",[]}.

%% returns id
id() -> "IDL:omg.org/CosTime/TimeUnavailable:1.0".

%% returns name
name() -> "CosTime_TimeUnavailable".



