%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_HRL).
-define(COSNOTIFYCOMM_HRL, true).


-record('CosNotifyComm_InvalidEventType', {'OE_ID'="IDL:omg.org/CosNotifyComm/InvalidEventType:1.0", type}).


-endif.


