%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosNotifyChannelAdmin_AdminLimitExceeded
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosNotifyChannelAdmin_AdminLimitExceeded').
-ic_compiled("4_4_2").


-include("CosNotifyChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosNotifyChannelAdmin/AdminLimitExceeded:1.0",
                   "AdminLimitExceeded",
                   [{"admin_property_err",
                     {tk_struct,"IDL:omg.org/CosNotifyChannelAdmin/AdminLimit:1.0",
                                "AdminLimit",
                                [{"name",{tk_string,0}},{"value",tk_any}]}}]}.

%% returns id
id() -> "IDL:omg.org/CosNotifyChannelAdmin/AdminLimitExceeded:1.0".

%% returns name
name() -> "CosNotifyChannelAdmin_AdminLimitExceeded".



