%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_cosNotificationAppComm
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosNotification/src/cosNotificationAppComm.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATIONAPPCOMM_HRL).
-define(OE_COSNOTIFICATIONAPPCOMM_HRL, true).




-endif.


