%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_NotifySubscribe
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_NOTIFYSUBSCRIBE_HRL).
-define(COSNOTIFYCOMM_NOTIFYSUBSCRIBE_HRL, true).




-endif.


