%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_HRL).
-define(COSEVENTCOMM_HRL, true).


-record('CosEventComm_Disconnected', {'OE_ID'="IDL:omg.org/CosEventComm/Disconnected:1.0"}).


-endif.


