%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_HRL).
-define(COSEVENTCHANNELADMIN_HRL, true).


-record('CosEventChannelAdmin_AlreadyConnected', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0"}).
-record('CosEventChannelAdmin_TypeError', {'OE_ID'="IDL:omg.org/CosEventChannelAdmin/TypeError:1.0"}).


-endif.


