%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: CosEventChannelAdmin_AlreadyConnected
%% Source: /home/centos/.asdf/plugins/erlang/kerl-home/builds/asdf_19.3/otp_src_19.3/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4.2
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('CosEventChannelAdmin_AlreadyConnected').
-ic_compiled("4_4_2").


-include("CosEventChannelAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_except,"IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0",
                   "AlreadyConnected",[]}.

%% returns id
id() -> "IDL:omg.org/CosEventChannelAdmin/AlreadyConnected:1.0".

%% returns name
name() -> "CosEventChannelAdmin_AlreadyConnected".



